(org-babel-do-load-languages
'org-babel-load-languages
 '((R . t)
   (emacs-lisp . t)
   (sql . t)
   (python . t)
   (latex . t)
   (shell . t)
   (java . t)
   (C . t)
   (lisp . t)
   ;; (stan . t)
   ))
(setq org-confirm-babel-evaluate nil)
(setq org-default-notes-file "~/Dropbox/Notes/notes.org")
(add-hook 'prog-mode-hook 'flyspell-prog-mode)
